#!/bin/sh

DECAC_HOME=$(cd "$(dirname "$0")"/../../../../ && pwd)
CP_FILE="$DECAC_HOME"/target/generated-sources/classpath.txt

CP="$DECAC_HOME"/target/generated-classes/cobertura:"$DECAC_HOME"/target/test-classes/:"$DECAC_HOME"/target/classes/:$(cat "$CP_FILE")
red=`tput setaf 1`
green=`tput setaf 2`
grey=`tput setaf 8`
reset=`tput sgr0`
effectues=0
total=0

cd $DECAC_HOME/src/test/deca/syntax/invalid/created



for prog in *.deca
do
    echo "Test de ${prog%.*}..."
    ((total++))
    test_synt $prog
    echo "Test effectué"
	((effectues++))
done

echo "$effectues tests effectués sur $total"


exit
