#!/bin/sh

DECAC_HOME=$(cd "$(dirname "$0")"/../../../../ && pwd)
CP_FILE="$DECAC_HOME"/target/generated-sources/classpath.txt

CP="$DECAC_HOME"/target/generated-classes/cobertura:"$DECAC_HOME"/target/test-classes/:"$DECAC_HOME"/target/classes/:$(cat "$CP_FILE")
red=`tput setaf 1`
green=`tput setaf 2`
grey=`tput setaf 8`
reset=`tput sgr0`
reussis=0
total=0

cd $DECAC_HOME/src/test/java/fr/ensimag/deca/syntax/Tests_oracle

mkdir -p expected
rm expected/*
mkdir -p obtained
rm obtained/*


for prog in *.java
do
    echo "Test de ${prog%.*}..."
    
    gen_expected_synt fr.ensimag.deca.syntax.Tests_oracle.${prog%.*}
    # Si le diff est vide, alors le test est réussi
    DIFF=$(diff -u expected/${prog%.*}.txt obtained/${prog%.*}.txt)
    if [$DIFF == ""]
    then
        echo "${green}Test réussi${reset}"
        ((reussis++))
    else
        echo "${red}Test échoué${reset}"
        echo "${grey}Obtenu                              Attendu${reset}"
        # Affiche les deux fichiers sur deux colonnes
        pr -m -t expected/${prog%.*}.txt obtained/${prog%.*}.txt
        # diff  ../expected/${prog%.*}.txt obtained/${prog%.*}.txt
    fi
    ((total++))
done

echo "$reussis tests réussis sur $total"


exit
