#!/bin/sh

DECAC_HOME=$(cd "$(dirname "$0")"/../../../../ && pwd)
CP_FILE="$DECAC_HOME"/target/generated-sources/classpath.txt

CP="$DECAC_HOME"/target/generated-classes/cobertura:"$DECAC_HOME"/target/test-classes/:"$DECAC_HOME"/target/classes/:$(cat "$CP_FILE")
red=`tput setaf 1`
green=`tput setaf 2`
grey=`tput setaf 8`
reset=`tput sgr0`
reussis=0
total=0

tmpfile=$(mktemp /tmp/temp.XXX)


cd $DECAC_HOME

ABSOPATH=$(pwd);

cd $DECAC_HOME/src/test/deca/codegen/valid/created


for prog in *.deca
do
    echo "Test de ${prog%.*}..."
    decac -a $ABSOPATH/src/test/deca/codegen/valid/created/$prog
    ima $ABSOPATH/src/test/deca/codegen/valid/created/${prog%.*}.ass > $tmpfile

    DIFF=$(diff -u ../expected/${prog%.*}.txt $tmpfile)
    if [$DIFF == ""]
    then
        echo "${green}Test réussi${reset}"
        ((reussis++))
    else
        echo "${red}Test échoué${reset}"
        echo "${grey}Obtenu                              Attendu${reset}"
        # Affiche les deux fichiers sur deux colonnes
        pr -m -t $tmpfile ../expected/${prog%.*}.txt
        # diff  ../alexpected/${prog%.*}.txt $tmpfile
    fi
    tmpfile=$(mktemp /tmp/temp.XXX)
    ((total++))
done

echo "$reussis tests réussis sur $total"

exit
