decac -v ../syntax/valid/created/assign.deca
decac -v ../syntax/valid/created/assign_assign_plus.deca
decac -v ../syntax/valid/created/assign_string.deca
decac -v ../syntax/valid/created/cast.deca
decac -v ../syntax/valid/created/cast_multiple.deca
decac -v ../syntax/valid/created/class_appel.deca
decac -v ../syntax/valid/created/class_appel_multiple.deca
decac -v ../syntax/valid/created/class_attribut.deca
decac -v ../syntax/valid/created/class_attribute_init.deca
decac -v ../syntax/valid/created/class_attribute_method.deca
decac -v ../syntax/valid/created/class_attribut_visibility.deca
decac -v ../syntax/valid/created/class_complex.deca
decac -v ../syntax/valid/created/class_extends.deca
decac -v ../syntax/valid/created/class_extends_itself.deca
decac -v ../syntax/valid/created/class_extends_queue.deca
decac -v ../syntax/valid/created/class_methodbody_inst_decl.deca
decac -v ../syntax/valid/created/class_methodbody_return.deca
decac -v ../syntax/valid/created/class_method.deca
decac -v ../syntax/valid/created/class_method_param.deca
decac -v ../syntax/valid/created/class_method_param_instruction.deca
decac -v ../syntax/valid/created/class_method_return_void.deca
decac -v ../syntax/valid/created/class_mult_attribut_init.deca
decac -v ../syntax/valid/created/class_multiple_attr_meth.deca
decac -v ../syntax/valid/created/class_mutliples.deca
decac -v ../syntax/valid/created/class_simple.deca
decac -v ../syntax/valid/created/class_syntax_identifier.deca
decac -v ../syntax/valid/created/class_syntax_identifier_extends.deca
decac -v ../syntax/valid/created/class_use_attribut.deca
decac -v ../syntax/valid/created/commentaire.deca
decac -v ../syntax/valid/created/commentaire_entre_deux.deca
decac -v ../syntax/valid/created/commentaire_multi_line_comment.deca
decac -v ../syntax/valid/created/commentaire_multi_line.deca
decac -v ../syntax/valid/created/commentaire_multi_line_dehors.deca
decac -v ../syntax/valid/created/commentaire_simple.deca
decac -v ../syntax/valid/created/decac_test.deca
decac -v ../syntax/valid/created/different.deca
decac -v ../syntax/valid/created/divide.deca
decac -v ../syntax/valid/created/dot.deca
decac -v ../syntax/valid/created/eq_neq.deca
decac -v ../syntax/valid/created/exclam.deca
decac -v ../syntax/valid/created/float.deca
decac -v ../syntax/valid/created/greaterorequals.deca
decac -v ../syntax/valid/created/greaterthan.deca
decac -v ../syntax/valid/created/ifelse.deca
decac -v ../syntax/valid/created/ifthenelse.deca
decac -v ../syntax/valid/created/ifthenelse++.deca
decac -v ../syntax/valid/created/include_multiple.deca
decac -v ../syntax/valid/created/include_multiple_suite.deca
decac -v ../syntax/valid/created/include_one.deca
decac -v ../syntax/valid/created/include_suite1.deca
decac -v ../syntax/valid/created/include_suite2.deca
decac -v ../syntax/valid/created/include_suite.deca
decac -v ../syntax/valid/created/include_two.deca
decac -v ../syntax/valid/created/inclu_math.deca
decac -v ../syntax/valid/created/inclu_multiple1.deca
decac -v ../syntax/valid/created/inclu_multiple2.deca
decac -v ../syntax/valid/created/inclu_mult_suite1.deca
decac -v ../syntax/valid/created/inclu_mult_suite2.deca
decac -v ../syntax/valid/created/inclu_mult_suite3.deca
decac -v ../syntax/valid/created/instanceof.deca
decac -v ../syntax/valid/created/int.deca
decac -v ../syntax/valid/created/int-float.deca
decac -v ../syntax/valid/created/isImplicit.deca
decac -v ../syntax/valid/created/just-an-int.deca
decac -v ../syntax/valid/created/lower.deca
decac -v ../syntax/valid/created/lowerorequals.deca
decac -v ../syntax/valid/created/methodAsm.deca
decac -v ../syntax/valid/created/methode_appel.deca
decac -v ../syntax/valid/created/minus.deca
decac -v ../syntax/valid/created/modulo.deca
decac -v ../syntax/valid/created/moitie.deca
decac -v ../syntax/valid/created/new.deca
decac -v ../syntax/valid/created/null.deca
decac -v ../syntax/valid/created/operation.deca
decac -v ../syntax/valid/created/or.deca
decac -v ../syntax/valid/created/parentheses.deca
decac -v ../syntax/valid/created/percent.deca
decac -v ../syntax/valid/created/plus_plus.deca
decac -v ../syntax/valid/created/print_argument.deca
decac -v ../syntax/valid/created/print.deca
decac -v ../syntax/valid/created/print_ident.deca
decac -v ../syntax/valid/created/printlnx.deca
decac -v ../syntax/valid/created/printlnx_lots_of_argument.deca
decac -v ../syntax/valid/created/print_lots_of_argument.deca
decac -v ../syntax/valid/created/print_no_argument.deca
decac -v ../syntax/valid/created/printx.deca
decac -v ../syntax/valid/created/prog_cours.deca
decac -v ../syntax/valid/created/readfloat.deca
decac -v ../syntax/valid/created/readint.deca
decac -v ../syntax/valid/created/semi.deca
decac -v ../syntax/valid/created/slash.deca
decac -v ../syntax/valid/created/this.deca
decac -v ../syntax/valid/created/times.deca
decac -v ../syntax/valid/created/unary.deca
decac -v ../syntax/valid/created/void-commented.deca
decac -v ../syntax/valid/created/void-main.deca
decac -v ../syntax/valid/created/while.deca
