#! /bin/sh

decac -a ../deca/codegen/valid/created/assign.deca
decac -a ../deca/codegen/valid/created/bool10.deca
decac -a ../deca/codegen/valid/created/bool11.deca
decac -a ../deca/codegen/valid/created/bool12.deca
decac -a ../deca/codegen/valid/created/bool13.deca
decac -a ../deca/codegen/valid/created/bool1.deca
decac -a ../deca/codegen/valid/created/bool2.deca
decac -a ../deca/codegen/valid/created/bool3.deca
decac -a ../deca/codegen/valid/created/bool4.deca
decac -a ../deca/codegen/valid/created/bool5.deca
decac -a ../deca/codegen/valid/created/bool6.deca
decac -a ../deca/codegen/valid/created/bool7.deca
decac -a ../deca/codegen/valid/created/bool8.deca
decac -a ../deca/codegen/valid/created/bool9.deca
decac -a ../deca/codegen/valid/created/boolassign10.deca
decac -a ../deca/codegen/valid/created/boolassign11.deca
decac -a ../deca/codegen/valid/created/boolassign12.deca
decac -a ../deca/codegen/valid/created/boolassign13.deca
decac -a ../deca/codegen/valid/created/boolassign14.deca
decac -a ../deca/codegen/valid/created/boolassign15.deca
decac -a ../deca/codegen/valid/created/boolassign16.deca
decac -a ../deca/codegen/valid/created/boolassign17.deca
decac -a ../deca/codegen/valid/created/boolassign1.deca
decac -a ../deca/codegen/valid/created/boolassign2.deca
decac -a ../deca/codegen/valid/created/boolassign3.deca
decac -a ../deca/codegen/valid/created/boolassign4.deca
decac -a ../deca/codegen/valid/created/boolassign5.deca
decac -a ../deca/codegen/valid/created/boolassign6.deca
decac -a ../deca/codegen/valid/created/boolassign7.deca
decac -a ../deca/codegen/valid/created/boolassign8.deca
decac -a ../deca/codegen/valid/created/boolassign9.deca
decac -a ../deca/codegen/valid/created/boolean.deca
decac -a ../deca/codegen/valid/created/compare10.deca
decac -a ../deca/codegen/valid/created/compare11.deca
decac -a ../deca/codegen/valid/created/compare12.deca
decac -a ../deca/codegen/valid/created/compare13.deca
decac -a ../deca/codegen/valid/created/compare14.deca
decac -a ../deca/codegen/valid/created/compare15.deca
decac -a ../deca/codegen/valid/created/compare16.deca
decac -a ../deca/codegen/valid/created/compare17.deca
decac -a ../deca/codegen/valid/created/compare1.deca
decac -a ../deca/codegen/valid/created/compare2.deca
decac -a ../deca/codegen/valid/created/compare3.deca
decac -a ../deca/codegen/valid/created/compare4.deca
decac -a ../deca/codegen/valid/created/compare5.deca
decac -a ../deca/codegen/valid/created/compare6.deca
decac -a ../deca/codegen/valid/created/compare7.deca
decac -a ../deca/codegen/valid/created/compare8.deca
decac -a ../deca/codegen/valid/created/compare9.deca
decac -a ../deca/codegen/valid/created/decac_test.deca
decac -a ../deca/codegen/valid/created/divide.deca
decac -a ../deca/codegen/valid/created/equals.deca
decac -a ../deca/codegen/valid/created/float10.deca
decac -a ../deca/codegen/valid/created/float11.deca
decac -a ../deca/codegen/valid/created/float12.deca
decac -a ../deca/codegen/valid/created/float13.deca
decac -a ../deca/codegen/valid/created/float1.deca
decac -a ../deca/codegen/valid/created/float2.deca
decac -a ../deca/codegen/valid/created/float3.deca
decac -a ../deca/codegen/valid/created/float4.deca
decac -a ../deca/codegen/valid/created/float5.deca
decac -a ../deca/codegen/valid/created/float6.deca
decac -a ../deca/codegen/valid/created/float7.deca
decac -a ../deca/codegen/valid/created/float8.deca
decac -a ../deca/codegen/valid/created/float9.deca
decac -a ../deca/codegen/valid/created/greater.deca
decac -a ../deca/codegen/valid/created/greaterOrEqual.deca
decac -a ../deca/codegen/valid/created/ifThenElse.deca
decac -a ../deca/codegen/valid/created/inst10.deca
decac -a ../deca/codegen/valid/created/inst11.deca
decac -a ../deca/codegen/valid/created/inst12.deca
decac -a ../deca/codegen/valid/created/inst13.deca
decac -a ../deca/codegen/valid/created/inst14.deca
decac -a ../deca/codegen/valid/created/inst15.deca
decac -a ../deca/codegen/valid/created/inst16.deca
decac -a ../deca/codegen/valid/created/inst17.deca
decac -a ../deca/codegen/valid/created/inst18.deca
decac -a ../deca/codegen/valid/created/inst19.deca
decac -a ../deca/codegen/valid/created/inst1.deca
decac -a ../deca/codegen/valid/created/inst20.deca
decac -a ../deca/codegen/valid/created/inst21.deca
decac -a ../deca/codegen/valid/created/inst22.deca
decac -a ../deca/codegen/valid/created/inst2.deca
decac -a ../deca/codegen/valid/created/inst3.deca
decac -a ../deca/codegen/valid/created/inst4.deca
decac -a ../deca/codegen/valid/created/inst5.deca
decac -a ../deca/codegen/valid/created/inst6.deca
decac -a ../deca/codegen/valid/created/inst7.deca
decac -a ../deca/codegen/valid/created/inst8.deca
decac -a ../deca/codegen/valid/created/inst9.deca
decac -a ../deca/codegen/valid/created/int10.deca
decac -a ../deca/codegen/valid/created/int1.deca
decac -a ../deca/codegen/valid/created/int2.deca
decac -a ../deca/codegen/valid/created/int3.deca
decac -a ../deca/codegen/valid/created/int4.deca
decac -a ../deca/codegen/valid/created/int5.deca
decac -a ../deca/codegen/valid/created/int6.deca
decac -a ../deca/codegen/valid/created/int7.deca
decac -a ../deca/codegen/valid/created/int8.deca
decac -a ../deca/codegen/valid/created/int9.deca
decac -a ../deca/codegen/valid/created/int.deca
decac -a ../deca/codegen/valid/created/lower.deca
decac -a ../deca/codegen/valid/created/lowerOrEqual.deca
decac -a ../deca/codegen/valid/created/minus.deca
decac -a ../deca/codegen/valid/created/mult10.deca
decac -a ../deca/codegen/valid/created/mult1.deca
decac -a ../deca/codegen/valid/created/mult2.deca
decac -a ../deca/codegen/valid/created/mult3.deca
decac -a ../deca/codegen/valid/created/mult4.deca
decac -a ../deca/codegen/valid/created/mult5.deca
decac -a ../deca/codegen/valid/created/mult6.deca
decac -a ../deca/codegen/valid/created/mult7.deca
decac -a ../deca/codegen/valid/created/mult8.deca
decac -a ../deca/codegen/valid/created/mult9.deca
decac -a ../deca/codegen/valid/created/multiply.deca
decac -a ../deca/codegen/valid/created/not.deca
decac -a ../deca/codegen/valid/created/notEquals.deca
decac -a ../deca/codegen/valid/created/or.deca
decac -a ../deca/codegen/valid/created/plus10.deca
decac -a ../deca/codegen/valid/created/plus1.deca
decac -a ../deca/codegen/valid/created/plus2.deca
decac -a ../deca/codegen/valid/created/plus3.deca
decac -a ../deca/codegen/valid/created/plus4.deca
decac -a ../deca/codegen/valid/created/plus5.deca
decac -a ../deca/codegen/valid/created/plus6.deca
decac -a ../deca/codegen/valid/created/plus7.deca
decac -a ../deca/codegen/valid/created/plus8.deca
decac -a ../deca/codegen/valid/created/plus9.deca
decac -a ../deca/codegen/valid/created/plus.deca
decac -a ../deca/codegen/valid/created/print.deca
decac -a ../deca/codegen/valid/created/println.deca
decac -a ../deca/codegen/valid/created/unaryMinus.deca
decac -a ../deca/codegen/valid/created/voidMain.deca
decac -a ../deca/codegen/valid/created/while.deca
